### PR TITLE
Image classifier

### PR DESCRIPTION
**Pull request by ashwinvijayakumar**
This is a sample code that accompanies https://movidius.github.io/blog/ncs-image-classifier/

### CODE REVIEW

**Comment by nealvis** [comment]
In your Makefile I didn't see it making ncappzoo/data/ilsvrc12 but I think you are reading the categories from there.   Do you want to add that?

**Comment by nealvis** [comment]
A few other comments.  I notice you are hardcoding the image mean RGB values in the code which I don't blame you for, I think i did it in some examples too.  But the more standard way to do it is using the ilsvrc_2012_mean.npy to get the three values.  Just throwing that out there.

Also, I think you can remove the standard deviation.  It came from the original Movidius examples but was only used to scale the data since some networks expect it between 0.0 and 1.0 and others between 0 and 255.

**Comment by ashwinvijayakumar** [comment]
@nealvis, I updated the Makefile to call ilsvrc12/Makefile per your recommendation. As for the hard coded mean & stdev values - I did that on purpose (enable scalability of the app across networks that don't have a npy mean file or has a scaling factor).

**Comment by 9600** [comment]
@ashwinvijayakumar firstly, apologies, as I appreciate this is not the best place to post this, however your repo fork used in:

https://movidius.github.io/blog/deploying-custom-caffe-models/

Does not have an issue tracker and I cannot see how else to contact you...

The issue with following the example in your blog post, is that the compute_image_mean step does not emit any BGR mean values, so how are we to follow this with our own training image sets?

**Pull request merged**
