### PR TITLE
made changes to ensure float calculations for python2

### PR DESCRIPTION
**Pull request by tomevang**

### CODE REVIEW

**Comment by nealvis** [comment]
Hi Tome,

I tried to test the projects affected by this PR and when i tested inception_v2 I get the following with this PR but it seemed to work without the change:

1) 1000 nan
2) 328 nan
3) 341 nan
4) 340 nan
5) 339 nan
Expected:  (1, 1001)
1) 947 0.999625
2) 808 0.000375067
3) 791 1.48096e-09
4) 229 1.08099e-11
5) 790 3.16383e-13
/usr/local/bin/ncsdk/Controllers/Metrics.py:75: RuntimeWarning: invalid value encountered in greater
  diff)) / total_values * 100
------------------------------------------------------------
 Obtained values 
------------------------------------------------------------
 Obtained Min Pixel Accuracy: nan% (max allowed=2%), Fail
 Obtained Average Pixel Accuracy: nan% (max allowed=1%), Fail
 Obtained Percentage of wrong values: 0.0% (max allowed=0%), Fail
 Obtained Pixel-wise L2 error: nan% (max allowed=1%), Fail
 Obtained Global Sum Difference: nan
------------------------------------------------------------

**Comment by nealvis** [comment]
Hey Tome, there was a change in the master that addressed this issue.  when i merge your PR with the current master the problem goes away so I think its good to merge

**Comment by tomevang** [comment]
will make new pr with updated branch

**Comment by nealvis** [comment]
You don't actually need to create a new PR, it will merge in to the master.

**Pull request merged**
