### PR TITLE
Food app

### PR DESCRIPTION
**Pull request by fcr3**
Accompanying app for food detection model. Doesn't need node!

### CODE REVIEW

**Comment by nealvis** [comment]
# Makefile Comments
## make clean
**make clean** should never fail.  If i run `make clean` as the first thing after cloning its failing.  Also make clean shouldn't uninstall anything.  Although i do like the idea of an **uninstall-reqs** target for that purpose.  I'll add that to makefile guidance.  Can you move the uninstall stuff to happen during  `make uninstall-reqs` ?

# make run
It looks like `make run` is installing flask and pillow.  Executing `make run` should never install anything.  use the `make install-reqs` target for that.  But the `make run` should detect if there are missing components and then output an error that instructs the user to do `make install-reqs`
After `make run` installed the things it installed error's out with a permission problem:
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/Werkzeug-0.14.1.dist-info/DESCRIPTION.rst' -> '/tmp/pip-hl_l6g4n-uninstall/usr/local/lib/python3.5/dist-packages/Werkzeug-0.14.1.dist-info/DESCRIPTION.rst'
```

**Comment by nealvis** [comment]
make clean is better. 

make run output:
Chef App: Running the sample...
Please make sure to fill in the config values for the Edamam API!
Setting up OpenVINO environment...
/opt/intel/openvino/bin/setupvars.sh
make: /opt/intel/openvino/bin/setupvars.sh: Command not found
Makefile:135: recipe for target 'run' failed
make: *** [run] Error 127
ncs@ncs-XPS-15-9550:~/repos/ncappzoo-test/ncappzoo/apps/chef_app$ ls /opt/intel
ls: cannot access '/opt/intel': No such file or directory

**Comment by nealvis** [comment]
After removing the call to setupvars.sh in the Makefile, i ran it.  clicking the CPU button gets this output in the server window though:
```
 * Serving Flask app "chef_ai_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-443-383
127.0.0.1 - - [12/Aug/2019 07:19:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Aug/2019 07:19:05] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2019 07:20:33] "POST /detect HTTP/1.1" 202 -
127.0.0.1 - - [12/Aug/2019 07:20:53] "POST /detect HTTP/1.1" 202 -
127.0.0.1 - - [12/Aug/2019 07:21:37] "POST /detect HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ncs/repos/ncappzoo-test/ncappzoo/apps/chef_app/chef_ai_server.py", line 119, in detect
    task = object_detection(img_base64, model, device)
  File "/home/ncs/repos/ncappzoo-test/ncappzoo/apps/chef_app/chef_ai_server.py", line 72, in object_detection
    obj_plugin.add_cpu_extension(ext)
  File "ie_api.pyx", line 584, in openvino.inference_engine.ie_api.IEPlugin.add_cpu_extension
    
  File "ie_api.pyx", line 588, in openvino.inference_engine.ie_api.IEPlugin.add_cpu_extension
    
RuntimeError: Cannot load library '/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so': /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so: cannot open shared object file: No such file or directory
127.0.0.1 - - [12/Aug/2019 07:21:58] "POST /detect HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ncs/repos/ncappzoo-test/ncappzoo/apps/chef_app/chef_ai_server.py", line 119, in detect
    task = object_detection(img_base64, model, device)
  File "/home/ncs/repos/ncappzoo-test/ncappzoo/apps/chef_app/chef_ai_server.py", line 72, in object_detection
    obj_plugin.add_cpu_extension(ext)
  File "ie_api.pyx", line 584, in openvino.inference_engine.ie_api.IEPlugin.add_cpu_extension
    
  File "ie_api.pyx", line 588, in openvino.inference_engine.ie_api.IEPlugin.add_cpu_extension
    
RuntimeError: Cannot load library '/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so': /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so: cannot open shared object file: No such file or directory
127.0.0.1 - - [12/Aug/2019 07:22:09] "POST /detect HTTP/1.1" 202 -
127.0.0.1 - - [12/Aug/2019 07:22:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Aug/2019 07:22:46] "GET /favicon.ico HTTP/1.1" 404 -

```

**Comment by nealvis** [comment]
- browser doesn't always connect to server because server not ready for connections.
- Server called chef_ai_server but project directory and makefile output still uses "chef app"
- Browser UI unclear how to use it.
- can you provide a few more input images, maybe some with multiple different items?

**Comment by nealvis** [comment]
with the name change commit: 


127.0.0.1 - - [13/Aug/2019 11:46:44] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ncs/repos/ncappzoo-test/ncappzoo/apps/chef_app/chef_ai_server.py", line 38, in index
    
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
127.0.0.1 - - [13/Aug/2019 11:46:44] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [13/Aug/2019 11:46:44] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Aug/2019 11:46:44] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Aug/2019 11:46:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by fcr3** [comment]
> with the name change commit:
> 
> 127.0.0.1 - - [13/Aug/2019 11:46:44] "GET / HTTP/1.1" 500 -
> Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2463, in **call**
> return self.wsgi_app(environ, start_response)
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2449, in wsgi_app
> response = self.handle_exception(e)
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1866, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
> raise value
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
> raise value
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/home/ncs/repos/ncappzoo-test/ncappzoo/apps/chef_app/chef_ai_server.py", line 38, in index
> 
> File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 138, in render_template
> ctx.app.jinja_env.get_or_select_template(template_name_or_list),
> File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
> return self.get_template(template_name_or_list, parent, globals)
> File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
> return self._load_template(name, self.make_globals(globals))
> File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
> template = self.loader.load(self, name, globals)
> File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 113, in load
> source, filename, uptodate = self.get_source(environment, name)
> File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 60, in get_source
> return self._get_source_fast(environment, template)
> File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 89, in _get_source_fast
> raise TemplateNotFound(template)
> jinja2.exceptions.TemplateNotFound: index.html
> 127.0.0.1 - - [13/Aug/2019 11:46:44] "GET /?**debugger**=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Aug/2019 11:46:44] "GET /?**debugger**=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Aug/2019 11:46:44] "GET /?**debugger**=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Aug/2019 11:46:45] "GET /?**debugger**=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

I seriously have no idea what's going on here. From the error messages, I see that there is no index.html file found. Did you somehow delete the index.html file from the templates folder? If this doesn't resolve itself, I will go back to the regular xdg-open way with a time delay.

**Comment by tomepetty** [comment]
Here are my recommendations:

1. Delete the line of that tries to set the openvino environment variables (line 140). I was able to run the sample after removing this line of code. 
2. Put install-reqs as a dependency for make run
3. Maybe a few more comments in the code
4. Maybe a brief overview description in your readme about what your app does.

**Comment by nealvis** [comment]
- The app directory is called chef_ai but the README.md says chef.AI lite.  This was confusing as to where is chef ai regular (non lite)  i didn't see that explained, so suggest explaining it or changeing readme.
- The .gif files are nice but they are too big to keep in the repository.  See if you can get them down to less than 1 MB or maybe 2MB at most.  I've had luck with this online tool to optimize gifs: www.ezgif.com.  If you cant get it small enough see if you can host it somewhere else.  I'm actually going through the repo now and removing some of the older binary files that were accidentally committed or committed without regard to size.  This is probably a new guideline that should go in the contributing.md file.
- also i wasn't clear as to why there are two .gif files, one for chef_ai and one for chef_ai_lite? They look very similar to me.
- The README.md says: 
> Go to Edamam API's website and register for an account. You will need to sign up for their recipe API as well as make an application that uses the recipe API

But i didn't do that and everything ran or seemed to run.  Is it using some default login?  Will that login remain active for ever?  I'm assuming not, in which case users need to create their own accounts so we should integrate this requirement into `make install-reqs` such that we at least detect no account has ben set when `make run` is issued and if possible automate creating the account or provide instructions on how to create it when `make install-reqs` is issued.

**Comment by nealvis** [comment]
# When i run `make install-reqs` its telling me that 
> APP_KEY = ... Please paste or type in your Edamam app key into the APP_KEY variable located at the top of the Makefile.
which is correct but would be more appropriate when `make run` is issued.

# When I issue `make run` without setting the APP_KEY or APP_ID, I would expect to get the message telling me to "Please paste or type in your Edamam app key into the APP_KEY" but instead,  the browser pops up with this:
> The connection was reset
> The connection to the server was reset while the page was loading.
Also the terminal has this on it: 
```
----------------------------------------
usage: chef_ai_server.py [-e CPU_EXTENSION] [-i APP_ID] [-k APP_KEY]
chef_ai_server.py: error: argument -k/--app_key: expected one argument
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 36560)
Traceback (most recent call last):
  File "/usr/lib/python3.5/argparse.py", line 1767, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1973, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.5/argparse.py", line 1903, in consume_optional
    arg_count = match_argument(action, selected_patterns)
  File "/usr/lib/python3.5/argparse.py", line 2067, in _match_argument
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument -k/--app_key: expected one argument
```

**Comment by nealvis** [comment]
To summarize last comment ... 
- `make run` should detect missing stuff (packages to install, or APP_KEY etc.) and give clear message to user explaining how to remedy the situation.  Ideally the remedy is always just run `make install-reqs'
- `make install-reqs` should install missing stuff, or give clear instructions how to get it.  So for the APP_ID and APP_KEY, it would be ideal if `make install-reqs` prompted for these values and then edited the file/s that need them, but would be acceptable if it gave instructions on how to edit the file.

**Comment by fcr3** [comment]
> To summarize last comment ...
> 
> * `make run` should detect missing stuff (packages to install, or APP_KEY etc.) and give clear message to user explaining how to remedy the situation.  Ideally the remedy is always just run `make install-reqs'
> * `make install-reqs` should install missing stuff, or give clear instructions how to get it.  So for the APP_ID and APP_KEY, it would be ideal if `make install-reqs` prompted for these values and then edited the file/s that need them, but would be acceptable if it gave instructions on how to edit the file.

Hopefully the last fix works for checking app key and app id. I think I'll just stick with giving them instructions if they haven't filled the makefile variables out.

**Comment by nealvis** [comment]
make install-reqs is still treating missing APP ID and APP KEY as an error
```
Checking if there a non-empty Edamam API app ID and app key...
APP_KEY = ... Please paste or type in your Edamam app key into the APP_KEY variable located at the top of the Makefile.
Makefile:132: recipe for target 'install-reqs' failed
make: *** [install-reqs] Error 1
```

**Comment by fcr3** [comment]
> make install-reqs is still treating missing APP ID and APP KEY as an error
> 
> ```
> Checking if there a non-empty Edamam API app ID and app key...
> APP_KEY = ... Please paste or type in your Edamam app key into the APP_KEY variable located at the top of the Makefile.
> Makefile:132: recipe for target 'install-reqs' failed
> make: *** [install-reqs] Error 1
> ```

The error is intentional. I've been trying to look up a more graceful approach to exiting the script, but this requires nesting conditionals, which isn't very nice to look at :( suggestions?

**Comment by fcr3** [comment]
Looking at the conditionals in the Makefile, this is a programmed exit 1

**Comment by nealvis** [comment]
i guess my suggestion would be to change this: 
```
	@if [ -z "$(APP_KEY)" ] ; \
	then \
		echo "APP_KEY = $(APP_KEY)... Please paste or type in your Edamam app key into the APP_KEY variable located at the top of the Makefile." ; \
		exit 1 ; \
	else \
		echo "Provided a non-empty app key." ; \
	fi
	@if [ -z "$(APP_ID)" ] ; \
	then \
		echo "Please paste or type in your Edamam app ID into the APP_ID variable located at the top of the Makefile." ; \
		exit 1 ; \
	else \
		echo "Provided a non-empty app ID." ; \
	fi
```

to this: 
```
	@if [ -z "$(APP_KEY)" ] ; \
	then \
		echo "APP_KEY = $(APP_KEY)... Please paste or type in your Edamam app key into the APP_KEY variable located at the top of the Makefile." ; \
	else \
		echo "Provided a non-empty app key." ; \
	fi
	@if [ -z "$(APP_ID)" ] ; \
	then \
		echo "Please paste or type in your Edamam app ID into the APP_ID variable located at the top of the Makefile." ; \
	else \
		echo "Provided a non-empty app ID." ; \
	fi
```

**Comment by nealvis** [comment]
Looks good!

**Pull request merged**
