### PR TITLE
face_emotion_game: added readme and makefile for app

### PR DESCRIPTION
**Pull request by anabwan**
The make file still not finished

Signed-off-by: anabwan <ayoob.nabwani@intel.com>

### CODE REVIEW

**Comment by nealvis** [comment]
@anabwan can you divide this into two pull requests?
1. One pull request for just the network part of this which touches only `ncappzoo/networks/emotions-recognition-retail-0003 `  for this PR you probably only need 3 files: 
**README.md**, **Makefile**, **python or C++ program** that demonstrates  the network with some sample image. 
You can follow the example of `ncappzoo/networks/face_detection_retail_0004`  The network is a standalone project in the appzoo that can be used by multiple apps.
2. One pull request for the app which touches only `ncappzoo/apps/face_emotion_game`this PR will include a Makefile that will can call the network Makefile to get the IR for the emotion network.  you can look at the way this project works as an example: `ncappzoo/apps/gender_age/' 

Also in general look at the CONTRIBUTING.md and the MAKEFILE_GUIDANCE.md files in the top level directory for general instructions as well as the examples mentioned above

**Comment by anabwan** [comment]
@nealvis Done. please see latest commit..
also see new PR: https://github.com/movidius/ncappzoo/pull/323

**Comment by tomepetty** [comment]
PR 323 currently has a pending issue. Before this PR can be reviewed, that one must be fixed first since this app relies on that network

**Comment by anabwan** [comment]
@tomepetty fixed on PR#323
please let me know when you test this.. please note that in this PR there is no *.py file so in order to run the following command: 'make run' you should pull PR#300 (the py file is there)

**Comment by anabwan** [comment]
closed.. merged on PR#300

**Pull request closed without merging**
