### PR TITLE
Add ImageNet wnid downloader helper to topcoder_example

### PR DESCRIPTION
**Pull request by jon-sculley**
Signed-off-by: Jonathan Sculley <jonathanpsculley@gmail.com>

### CODE REVIEW

**Comment by nealvis** [comment]
@ashwinvijayakumar  can you review this change, if you approve I'll merge.

**Comment by nealvis** [comment]
@ashwinvijayakumar, can you take a look and approve?

**Comment by nealvis** [comment]
@yuanyuanli85 take a look.

**Comment by yuanyuanli85** [comment]
I took a look and verified this PR locally. It worked well. It tried to download the images with given wnid from imagenet , and created one fold in current directory to store those images.   

This PR looks fine to me. @nealvis @ashwinvijayakumar.

**Comment by ashwinvijayakumar** [comment]
Thanks for reviewing @yuanyuanli85. 
@nealvis, I think we can go ahead and merge this PR.

**Pull request merged**
