### PR TITLE
Food ssd inception v2 more

### PR DESCRIPTION
**Pull request by fcr3**
Training script using Tensorflow Object Detection

### CODE REVIEW

**Comment by DrewBearly** [comment]
@fcr3 There is just one more conflict with the Makefile that needs to be resolved.

**Comment by fcr3** [comment]
If you look at the editor for resolving conflicts, no actual lines are conflicting with one another... It's super weird...

**Comment by DrewBearly** [comment]
@fcr3 That is weird - it might be as simple as a single space offset or something _dumb_ like that. Have you checked the conflict in an editor like VSCode that has rich diff features? It should show exactly where the conflict is. That has helped me in the past.

**Comment by fcr3** [comment]
Hey I suppose I magically fixed it! Also I finished the training and compilation scripts. `make train` trains model while `make compile_from_training` freezes trained model and optimizes. README was also updated to reflect more make commands.

**Pull request merged**
