### PR TITLE
Graph File missing in caffe dir

### PR DESCRIPTION
**Pull request by sidagarwal04**
Graph file seems to be missing from AlexNet, GoogLeNet and GenderNet dir under ncappzoo/caffe/ and if I try to run the examples in the repo based on this [blog](https://movidius.github.io/blog/ncs-image-classifier/), it throws an error as below:
`FileNotFoundError: [Errno 2] No such file or directory: '../../caffe/GoogLeNet/graph'`

I tried adding Graph file explicitly from ncsdk/examples/caffe/GoogLeNet to ncappzoo/caffe/GoogLeNet to fix this issue. Would be great if the graph file can be included in directories when someone clones the repo using
`git clone https://github.com/movidius/ncappzoo`

### CODE REVIEW

**Comment by nealvis** [comment]
Hi @sidagarwal04,  The intent of the ncappzoo is to provide an easy way to create the graph files rather than actually check them into the repo.  I'm don't know about the blog, but @ashwinvijayakumar  may comment on that.  The neural network directories under ncappzoo/caffe, and ncappzoo/tensorflow all have make files and running 'make compile' should generate the graph file for that network.

**Comment by sidagarwal04** [comment]
Hi @nealvis, thanks for the response. Figured it out a bit late after opening this pull request. Make files does the job. However, I feel the documentation needs to be updated accordingly. I'll share my thoughts on the same in separate PR.

**Comment by nealvis** [comment]
Hi @sidagarwal04,  Glad you were able to figure out our intent and sorry it wasn't more obvious.  Thanks for taking the time to submit the PR on this.   I'm going to close this one but will look for a future PR from you with some suggested documentation changes.

**Comment by sidagarwal04** [comment]
H @nealvis , sure.

**Pull request closed without merging**
