### PR TITLE
Topcoder fsadu

### PR DESCRIPTION
**Pull request by saduf**
Files moved from Apps to Tensorflow directory.

### CODE REVIEW

**Comment by saduf** [comment]
Files moved from Apps to Tensorflow directory.

**Comment by m-georgiev** [comment]
Hello, can you please give some details about the point
"1. Decompress all the synsets into a training directory."
As you mentioned this is from ImageNet Fall 11 dataset but it is not clear to me where to download.
Can you give a link or a website to download? Thanks.

**Comment by saduf** [comment]
http://academictorrents.com/details/564a77c1e1119da199ff32622a1609431b9f1c47/tech&dllist=1

You can try academic torrents. Another option is to request an account at
Image-net.org.

**Comment by nealvis** [comment]
Hi @saduf,

Before i merget this PR, can you add a Makefile to the ncappzoo/tensorflow/topcoder_fsadu and ncappzoo/apps/topcoder_fsadu diretories?  you can look at some of the other projects for examples. 

Also, please take a look at the CONTRIBUTING.md file here:
https://github.com/movidius/ncappzoo/blob/master/CONTRIBUTING.md

and the Makefile guidance here: 
https://github.com/movidius/ncappzoo/blob/master/MAKEFILE_GUIDANCE.md

Thanks

**Comment by nealvis** [comment]
@yuanyuanli85, take a look

**Comment by saduf** [comment]
Hi Neal,

Do you think that we need a Makefile? If we are fine tuning the model, and
it depends on the accuracy and time we want for our application, then we
have to issue the training command depending on these parameters.

Please let me know your thoughts, and I will gladly write a Makefile in
case this is needed.

Fernando SaDu.

**Comment by nealvis** [comment]
Closing, never resolved Makefile

**Pull request closed without merging**
