### PR TITLE
Mobile SSD trained by VOC 10 classes

### PR DESCRIPTION
**Pull request by yuanyuanli85**
This PR adds one example for mobilenet-ssd trained by using 10 classes from VOC dataset.  The list of labels are described in `caffe/SSD_MobileNet_VOC_10Class/labels.txt`.  

@ashwinvijayakumar , Please help to review this PR.

### CODE REVIEW

**Comment by ashwinvijayakumar** [comment]
@yuanyuanli85, the caffe/SSD_MobileNet_VOC_10Class project doesn't seem to have the scripts needed to prep the dataset and start a training session. Can you please create a new pull request that has the scripts needed to prep dataset, train model and compile graph? Please use https://github.com/ashwinvijayakumar/ncappzoo/tree/dogs-vs-cats/apps/dogsvscats as a reference project.

Also, no need to create a dedicated app for running this model. ssd-object-detector can take model file and labels file via command line, so you can use that app as-is to run caffe/SSD_MobileNet_VOC_10Class.

**Comment by yuanyuanli85** [comment]
@ashwinvijayakumar 
1. will remove the duplicate apps/mobile-ssd-voc-10class.
2. For comments to add data perp and train into make, I have below concerns.  The data preparation is much more complex than dogsvscat. It has dependency on caffe/ssd, needs to run python scripts to generate the list of files, python script to filter out lables not in label list , generate the lmdb. .. Besides, training on voc takes more than 5 days to finish on a TitanXP.  I am worried about the makefile is going to be messy if we put all of these kind of things into it.

**Comment by nealvis** [comment]
Closing, the training doesn't work.

**Comment by nealvis** [comment]
Closing, for real this time

**Pull request closed without merging**
