### PR TITLE
Fix caffe makefile

### PR DESCRIPTION
**Pull request by ashwinvijayakumar**
Updated Caffe Makefiles to remove intermediate files generated in data directory.

This commit was tested by running the following sequence:

1. `cd apps/stream_infer`
2. `make`
3. `git status` will list all intermediate files created
4. `make clean`
5. `git status` will confirm that all intermediate files have been deleted

### CODE REVIEW

**Comment by ramanarachakonda** [comment]
Merging changes from Ashwin

**Comment by robmarkcole** [comment]
waiting on this.. Cheers

**Comment by nealvis** [comment]
I don't like the idea of one project's "make clean" cleaning other projects since the dependencies aren't known.  If there a strong desire for cleaning dependencies rather than just going going to the data directory and cleaning it separately  by running "make clean" in that directory (ie the data/ilsvrc12 directory) then I think we should start using something like "make clean_deps" so that its a deliberate command to clean the dependencies.

Thoughts?

**Comment by nealvis** [comment]
Closing per conversation with @ashwinvijayakumar

**Pull request closed without merging**
